id: IF8756F5F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T17:57:31+00:00'
last_modified: '2022-06-07T13:57:28.691902+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28843
  title: རྒྱུད་བཞིའི་རྣམ་བཤད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1EAC:
      image_group_id: I4711
      title: ''
      total_pages: 1272
      order: 1
      base_file: 1EAC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
