id: P001667
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W28843
  title: རྒྱུད་བཞིའི་རྣམ་བཤད
  author: ''
  volumes:
    64a4d7042d884809992fd774de0c453b:
      image_group_id: I4711
      title: ''
      volume_number: 1
      total_pages: 1272
      base_file: v001.txt
